# Generated by Django 5.1.4 on 2024-12-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='document',
            old_name='embeddings',
            new_name='embedding',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.DeleteModel(
            name='DocumentSelection',
        ),
    ]
